"""Phase 10 — quality test definitions + custom SQL guardrails.

This module is the single safety gate for "custom SQL" quality tests.
Enforces:
- SELECT-only
- one statement only (no semicolon chaining)
- no DML/DDL tokens (INSERT, UPDATE, DELETE, DROP, TRUNCATE, CREATE,
  MERGE, CALL, GRANT, REVOKE, ALTER)
- must reference the target entity FQN (or a whitelisted comparison)
- declared budgets are respected
- result schema is bounded (row_budget, byte_budget, time_budget_ms)

The built-in test keys (row_count, freshness, null_count, etc.) get
their SQL generated by this module, not by the caller.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Optional, Sequence

import pandas as pd

BUILTIN_TEST_KEYS = (
    "row_count",
    "freshness",
    "null_count",
    "null_fraction",
    "unique",
    "accepted_values",
    "regex",
    "min_max",
    "schema_column_presence",
    "custom_sql",
    "table_comparison",
)

FORBIDDEN_TOKENS = (
    "INSERT",
    "UPDATE",
    "DELETE",
    "DROP",
    "TRUNCATE",
    "CREATE",
    "MERGE",
    "CALL",
    "GRANT",
    "REVOKE",
    "ALTER",
    "OPTIMIZE",
    "VACUUM",
    "REFRESH",
    "COMMENT ON",
    "USE CATALOG",
    "USE SCHEMA",
)

# Max values we'll ever allow a caller to request. Individual plans may
# set smaller budgets.
MAX_ROW_BUDGET = 100_000
MAX_BYTE_BUDGET = 64 * 1024 * 1024  # 64 MiB
MAX_TIME_BUDGET_MS = 60_000  # 1 minute


@dataclass(frozen=True)
class CustomSqlValidation:
    ok: bool
    reason: str = ""
    normalized: str = ""


def _strip_comments(sql: str) -> str:
    # Remove /* ... */ block comments and -- line comments. Cheap enough
    # for pre-execution validation.
    block = re.sub(r"/\*.*?\*/", " ", sql, flags=re.S)
    line = re.sub(r"--[^\n]*", " ", block)
    return line


def validate_custom_sql(
    sql: str,
    *,
    target_entity_fqn: str,
    allowed_comparisons: Iterable[str] = (),
) -> CustomSqlValidation:
    if not sql or not sql.strip():
        return CustomSqlValidation(ok=False, reason="Custom SQL is empty.")
    cleaned = _strip_comments(sql).strip()
    # No trailing semicolons (reject chained statements).
    statements = [part for part in cleaned.split(";") if part.strip()]
    if len(statements) != 1:
        return CustomSqlValidation(
            ok=False,
            reason="Custom SQL must be a single statement (no ';' chaining).",
        )
    statement = statements[0].strip()
    upper = statement.upper()
    # SELECT-only.
    if not upper.startswith("SELECT") and not upper.startswith("WITH"):
        return CustomSqlValidation(
            ok=False,
            reason="Custom SQL must start with SELECT or WITH.",
        )
    for token in FORBIDDEN_TOKENS:
        pattern = r"\b" + re.escape(token) + r"\b"
        if re.search(pattern, upper):
            return CustomSqlValidation(
                ok=False,
                reason=f"Custom SQL may not contain {token}.",
            )
    # Must reference the target entity FQN (case-insensitive). We accept
    # either the fully-qualified form, the last two segments (schema.table),
    # or any allowed comparison entity.
    lowered = statement.lower()
    candidates = [target_entity_fqn.lower(), *[c.lower() for c in allowed_comparisons]]
    # allow schema.table if fqn has 3 segments
    if target_entity_fqn.count(".") >= 2:
        candidates.append(".".join(target_entity_fqn.split(".")[-2:]).lower())
    if not any(candidate in lowered for candidate in candidates if candidate):
        return CustomSqlValidation(
            ok=False,
            reason=(
                "Custom SQL must reference the target entity "
                f"({target_entity_fqn}) or an approved comparison entity."
            ),
        )
    return CustomSqlValidation(ok=True, normalized=statement)


@dataclass(frozen=True)
class BudgetCheck:
    ok: bool
    reason: str = ""
    row_budget: int = 0
    byte_budget: int = 0
    time_budget_ms: int = 0


def check_budgets(
    *,
    row_budget: Optional[int],
    byte_budget: Optional[int],
    time_budget_ms: Optional[int],
) -> BudgetCheck:
    row = int(row_budget or 0)
    byte = int(byte_budget or 0)
    ms = int(time_budget_ms or 0)
    if row < 0 or byte < 0 or ms < 0:
        return BudgetCheck(ok=False, reason="Budgets must be non-negative.")
    if row > MAX_ROW_BUDGET:
        return BudgetCheck(
            ok=False, reason=f"row_budget exceeds global cap ({MAX_ROW_BUDGET})."
        )
    if byte > MAX_BYTE_BUDGET:
        return BudgetCheck(
            ok=False, reason=f"byte_budget exceeds global cap ({MAX_BYTE_BUDGET})."
        )
    if ms > MAX_TIME_BUDGET_MS:
        return BudgetCheck(
            ok=False, reason=f"time_budget_ms exceeds global cap ({MAX_TIME_BUDGET_MS})."
        )
    return BudgetCheck(
        ok=True,
        row_budget=min(row or MAX_ROW_BUDGET, MAX_ROW_BUDGET),
        byte_budget=min(byte or MAX_BYTE_BUDGET, MAX_BYTE_BUDGET),
        time_budget_ms=min(ms or MAX_TIME_BUDGET_MS, MAX_TIME_BUDGET_MS),
    )


def summarize_run_results(
    results: List[Dict[str, Any]],
) -> Dict[str, int]:
    """Return counts per outcome for a quality_runs.summary_json value."""
    buckets = {"passed": 0, "failed": 0, "errored": 0, "skipped": 0}
    for record in results:
        outcome = str(record.get("outcome") or "").strip().lower()
        if outcome in buckets:
            buckets[outcome] += 1
    return buckets


# ---------------------------------------------------------------------------
# Quality findings (Wave A4 — the Evidence quality tab browse contract)
# ---------------------------------------------------------------------------

# Severity buckets MUST match atlas_metrics._quality_sla_signal so the same
# check never counts as "high" on one surface and "medium" on another
# (cohesion law: one number per concept).
_SEVERITY_HIGH = frozenset({"error", "critical", "high", "blocker"})
_SEVERITY_INFORMATIONAL = frozenset({"info", "informational", "low"})

# Outcomes the findings endpoint understands. "skipped" rows are browseable
# evidence too (they explain why a check produced no verdict).
FINDING_OUTCOMES = frozenset({"passed", "failed", "errored", "skipped"})

# The ledger fetch window: mirrors _quality_sla_signal's 2000-row read so the
# findings feed and the SLA tile are computed over the same evidence.
_FINDINGS_FETCH_WINDOW = 2000


def normalize_severity_level(severity: Any) -> str:
    """Map a raw stored severity to the canonical high/medium/informational
    bucket used across quality surfaces (same mapping as _quality_sla_signal)."""
    text = str(severity or "").strip().lower()
    if text in _SEVERITY_HIGH:
        return "high"
    if text in _SEVERITY_INFORMATIONAL:
        return "informational"
    return "medium"


def finding_display_id(result_id: Any, *, row: Optional[Dict[str, Any]] = None) -> str:
    """Stable customer-facing finding id, mirroring audit_display_id semantics.

    "QF-" + first 8 hex chars of the backing result uuid — NEVER positional, so
    the same finding keeps the same id across filters, exports, and deep links
    (`/evidence?tab=quality&...`). Rows with no usable id hash their content
    fingerprint instead; still stable, still never positional.
    """
    raw = str(result_id or "").strip()
    if raw:
        hex_chars = re.sub(r"[^0-9a-f]", "", raw.lower())
        if len(hex_chars) >= 8:
            return f"QF-{hex_chars[:8].upper()}"
        return f"QF-{hashlib.sha256(raw.encode('utf-8')).hexdigest()[:8].upper()}"
    if row is not None:
        fingerprint = "|".join(
            str(row.get(key) or "")
            for key in ("run_id", "case_id", "entity_fqn", "executed_at")
        )
        if fingerprint.strip("|"):
            return f"QF-{hashlib.sha256(fingerprint.encode('utf-8')).hexdigest()[:8].upper()}"
    return ""


def _utc_z(value: Any) -> str:
    """Normalize any stored timestamp to UTC ISO-8601 with an explicit Z.

    Quality evidence must never leave the API as a naive local time (the same
    contract the audit payloads follow). Returns "" when unparseable — never
    fabricates."""
    if value is None:
        return ""
    try:
        ts = pd.Timestamp(value)
    except (TypeError, ValueError):
        return ""
    if ts is pd.NaT:
        return ""
    if ts.tzinfo is None:
        ts = ts.tz_localize("UTC")
    else:
        ts = ts.tz_convert("UTC")
    return ts.isoformat().replace("+00:00", "Z")


def _parse_utc(value: Any) -> Optional[pd.Timestamp]:
    if value is None or str(value).strip() == "":
        return None
    try:
        ts = pd.Timestamp(str(value).strip())
    except (TypeError, ValueError):
        return None
    if ts is pd.NaT:
        return None
    if ts.tzinfo is None:
        ts = ts.tz_localize("UTC")
    else:
        ts = ts.tz_convert("UTC")
    return ts


def _frame_records(frame: Any) -> List[Dict[str, Any]]:
    try:
        if frame is None:
            return []
        if isinstance(frame, pd.DataFrame):
            return [] if frame.empty else frame.to_dict("records")
        return [dict(row) for row in frame]
    except Exception:
        return []


def _optional_float(value: Any) -> Optional[float]:
    if value is None:
        return None
    try:
        if pd.isna(value):
            return None
    except (TypeError, ValueError):
        pass
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _humanize_case_id(case_id: str) -> str:
    """Fallback check name derived from the case id itself.

    Seeded/curated case ids are descriptive slugs
    ("GOV-QUALITY-EVIDENCE-case-customer-profile-minimum-rows"); strip the
    bookkeeping prefix and title-case the rest. Opaque uuid case ids are NOT
    prettified — the raw id is more honest than a fake sentence."""
    text = str(case_id or "").strip()
    if not text:
        return ""
    # uuid-shaped ids stay verbatim: title-casing hex noise fabricates meaning.
    if re.fullmatch(r"[0-9a-fA-F]{16,}", text):
        return text
    cleaned = re.sub(r"(?i)^[A-Z0-9-]*-case-", "", text)
    words = [w for w in re.split(r"[-_]+", cleaned) if w]
    if not words:
        return text
    return " ".join(w if w.isupper() else w.capitalize() for w in words)


def _check_name_lookup(store: Any, case_ids: Sequence[str]) -> Dict[str, Dict[str, str]]:
    """case_id -> {"displayName", "testKey"} from the definitions tables.

    Degrades to an empty map when the store lacks the join method — the
    caller then falls back to the humanized case id and labels the source."""
    if store is None or not hasattr(store, "list_quality_check_names") or not case_ids:
        return {}
    try:
        frame = store.list_quality_check_names(case_ids=list(case_ids))
    except Exception:
        return {}
    lookup: Dict[str, Dict[str, str]] = {}
    for row in _frame_records(frame):
        case_id = str(row.get("case_id") or "").strip()
        if not case_id:
            continue
        lookup[case_id] = {
            "displayName": str(row.get("display_name") or "").strip(),
            "testKey": str(row.get("test_key") or "").strip(),
        }
    return lookup


def _run_metadata_lookup(store: Any) -> Dict[str, Dict[str, Any]]:
    """run_id -> run metadata (trigger/status/started/finished/suite).

    created_by is deliberately NOT exposed: findings are visibility-scoped by
    asset, not steward-gated, so actor identities stay out of this payload."""
    if store is None or not hasattr(store, "list_quality_runs"):
        return {}
    try:
        frame = store.list_quality_runs(limit=200)
    except Exception:
        return {}
    lookup: Dict[str, Dict[str, Any]] = {}
    for row in _frame_records(frame):
        run_id = str(row.get("run_id") or "").strip()
        if not run_id:
            continue
        lookup[run_id] = {
            "runId": run_id,
            "suiteId": str(row.get("suite_id") or "").strip(),
            "trigger": str(row.get("trigger") or "").strip(),
            "status": str(row.get("status") or "").strip(),
            "startedAt": _utc_z(row.get("started_at")),
            "finishedAt": _utc_z(row.get("finished_at")),
        }
    return lookup


def quality_findings(
    store: Any,
    *,
    asset_fqn: Optional[str] = None,
    severity: Optional[str] = None,
    outcome: Optional[str] = None,
    since: Optional[str] = None,
    until: Optional[str] = None,
    limit: int = 200,
    visible_asset_fqns: Optional[Sequence[str]] = None,
) -> Dict[str, Any]:
    """Filterable quality-run findings joined with run metadata.

    Reads the SAME quality_run_results ledger _quality_sla_signal scores, so
    the Evidence quality tab and the Command Center risk tiles can never
    disagree about what ran. Every row carries a stable finding id and a UTC
    "Z" executedAt. Rows about assets outside `visible_asset_fqns` are dropped
    (row-level visibility, same contract as audit evidence) and the exclusion
    is counted honestly instead of silently shrinking the feed.
    """
    limit = max(1, min(int(limit or 200), 500))
    asset_filter = str(asset_fqn or "").strip()
    severity_filter = str(severity or "").strip().lower()
    outcome_filter = str(outcome or "").strip().lower()
    since_ts = _parse_utc(since)
    until_ts = _parse_utc(until)

    if store is None or not hasattr(store, "list_quality_run_results"):
        return {
            "findings": [],
            "summary": None,
            "state": "unavailable",
            "reason": "Quality run ledger is not available from the governance store.",
            "windowTruncated": False,
            "visibilityScopedRowsExcluded": 0,
        }
    try:
        frame = store.list_quality_run_results(
            entity_fqn=asset_filter or None,
            limit=_FINDINGS_FETCH_WINDOW,
        )
    except Exception as exc:
        return {
            "findings": [],
            "summary": None,
            "state": "unavailable",
            "reason": f"Quality run ledger read failed: {str(exc).splitlines()[0][:300]}",
            "windowTruncated": False,
            "visibilityScopedRowsExcluded": 0,
        }
    fetched = _frame_records(frame)
    window_truncated = len(fetched) >= _FINDINGS_FETCH_WINDOW

    visible_lower: Optional[set] = None
    if visible_asset_fqns is not None:
        visible_lower = {
            str(fqn).strip().lower() for fqn in visible_asset_fqns if str(fqn).strip()
        }

    visibility_excluded = 0
    filtered: List[Dict[str, Any]] = []
    for row in fetched:
        entity = str(row.get("entity_fqn") or "").strip()
        # Row-level visibility: findings about assets outside the actor's
        # scope are withheld, counted, and never described further.
        if visible_lower is not None and entity and entity.lower() not in visible_lower:
            visibility_excluded += 1
            continue
        row_outcome = str(row.get("outcome") or "").strip().lower()
        if outcome_filter and row_outcome != outcome_filter:
            continue
        row_severity = str(row.get("severity") or "").strip().lower()
        row_level = normalize_severity_level(row_severity)
        # The filter accepts either the raw stored severity ("critical") or
        # the canonical bucket ("high") so deep links from the risk breakdown
        # (which speaks in buckets) resolve without a translation table.
        if severity_filter and severity_filter not in {row_severity, row_level}:
            continue
        executed = _parse_utc(row.get("executed_at"))
        if since_ts is not None and (executed is None or executed < since_ts):
            continue
        if until_ts is not None and (executed is None or executed > until_ts):
            continue
        filtered.append(row)

    limited = filtered[:limit]
    check_names = _check_name_lookup(
        store, [str(row.get("case_id") or "") for row in limited]
    )
    runs = _run_metadata_lookup(store)

    findings: List[Dict[str, Any]] = []
    outcome_counts = {"passed": 0, "failed": 0, "errored": 0, "skipped": 0}
    latest_evidence_ts: Optional[pd.Timestamp] = None
    for row in filtered:
        row_outcome = str(row.get("outcome") or "").strip().lower()
        if row_outcome in outcome_counts:
            outcome_counts[row_outcome] += 1
        executed = _parse_utc(row.get("executed_at"))
        if executed is not None and (
            latest_evidence_ts is None or executed > latest_evidence_ts
        ):
            latest_evidence_ts = executed
    latest_evidence = (
        latest_evidence_ts.isoformat().replace("+00:00", "Z")
        if latest_evidence_ts is not None
        else ""
    )
    for row in limited:
        case_id = str(row.get("case_id") or "").strip()
        named = check_names.get(case_id) or {}
        display_name = named.get("displayName") or ""
        run_id = str(row.get("run_id") or "").strip()
        metric_value = row.get("metric_value")
        threshold_value = row.get("threshold_value")
        detail = str(row.get("detail") or "").strip()
        findings.append(
            {
                "findingId": finding_display_id(row.get("result_id"), row=row),
                "resultId": str(row.get("result_id") or "").strip(),
                "runId": run_id,
                "executedAt": _utc_z(row.get("executed_at")),
                "assetFqn": str(row.get("entity_fqn") or "").strip(),
                "columnName": str(row.get("column_name") or "").strip(),
                "caseId": case_id,
                "checkName": display_name or _humanize_case_id(case_id),
                # Honesty marker: "definition" means the curated display name;
                # "case-id" means the name is derived from the id slug.
                "checkNameSource": "definition" if display_name else "case-id",
                "testKey": named.get("testKey") or "",
                "outcome": str(row.get("outcome") or "").strip().lower(),
                "severity": str(row.get("severity") or "").strip().lower(),
                "severityLevel": normalize_severity_level(row.get("severity")),
                # message is the recorded evaluator detail — never synthesized
                # prose. Empty stays empty; the UI renders its own fallback.
                "message": detail,
                "metricValue": _optional_float(metric_value),
                "thresholdValue": _optional_float(threshold_value),
                "run": runs.get(run_id),
            }
        )

    if not findings:
        reason = (
            "No quality findings match the requested filters."
            if fetched
            else "No quality checks have run yet. Configure expectations from an asset's Quality tab to activate this feed."
        )
        return {
            "findings": [],
            "summary": {
                "total": 0,
                "outcomes": outcome_counts,
                "evidenceAt": latest_evidence,
            },
            "state": "unavailable",
            "reason": reason,
            "windowTruncated": window_truncated,
            "visibilityScopedRowsExcluded": visibility_excluded,
        }
    return {
        "findings": findings,
        "summary": {
            # total counts the full filtered population, not just the page.
            "total": len(filtered),
            "returned": len(findings),
            "outcomes": outcome_counts,
            "evidenceAt": latest_evidence,
            "source": "quality_run_results",
        },
        "state": "available",
        "reason": "",
        "windowTruncated": window_truncated,
        "visibilityScopedRowsExcluded": visibility_excluded,
    }


def asset_quality_summary(store: Any, asset_fqn: str) -> Dict[str, Any]:
    """Per-asset quality composite block for the /360 payload.

    Latest-run outcome counts + the newest evidence timestamp, read from the
    same quality_run_results ledger _quality_sla_signal scores. "unavailable"
    ONLY when the ledger truly holds nothing for this asset."""
    fqn = str(asset_fqn or "").strip()
    if store is None or not hasattr(store, "list_quality_run_results") or not fqn:
        return {
            "state": "unavailable",
            "message": "Quality run ledger is not available from the governance store.",
            "latestRun": None,
            "evidenceAt": "",
            "checksEvaluated": 0,
        }
    try:
        frame = store.list_quality_run_results(entity_fqn=fqn, limit=500)
    except Exception as exc:
        return {
            "state": "unavailable",
            "message": f"Quality run ledger read failed: {str(exc).splitlines()[0][:300]}",
            "latestRun": None,
            "evidenceAt": "",
            "checksEvaluated": 0,
        }
    rows = _frame_records(frame)
    if not rows:
        return {
            "state": "unavailable",
            "message": "No quality checks have run for this asset.",
            "latestRun": None,
            "evidenceAt": "",
            "checksEvaluated": 0,
        }
    # Newest evidence + the run that produced it.
    latest_run_id = ""
    latest_ts: Optional[pd.Timestamp] = None
    for row in rows:
        executed = _parse_utc(row.get("executed_at"))
        if executed is not None and (latest_ts is None or executed > latest_ts):
            latest_ts = executed
            latest_run_id = str(row.get("run_id") or "").strip()
    latest_rows = [
        row for row in rows if str(row.get("run_id") or "").strip() == latest_run_id
    ]
    outcomes = summarize_run_results(latest_rows)
    failed_by_level = {"high": 0, "medium": 0, "informational": 0}
    for row in latest_rows:
        if str(row.get("outcome") or "").strip().lower() in {"failed", "errored"}:
            failed_by_level[normalize_severity_level(row.get("severity"))] += 1
    evidence_at = latest_ts.isoformat().replace("+00:00", "Z") if latest_ts is not None else ""
    return {
        "state": "available",
        "message": "",
        "latestRun": {
            "runId": latest_run_id,
            "executedAt": evidence_at,
            "outcomes": outcomes,
            "failedBySeverityLevel": failed_by_level,
            "checkCount": len(latest_rows),
        },
        "evidenceAt": evidence_at,
        "checksEvaluated": len(rows),
        "source": "quality_run_results",
    }
