"""Phase 10 — quality test definitions + custom SQL guardrails.

This module is the single safety gate for "custom SQL" quality tests.
Enforces:
- SELECT-only
- one statement only (no semicolon chaining)
- no DML/DDL tokens (INSERT, UPDATE, DELETE, DROP, TRUNCATE, CREATE,
  MERGE, CALL, GRANT, REVOKE, ALTER)
- must reference the target entity FQN (or a whitelisted comparison)
- declared budgets are respected
- result schema is bounded (row_budget, byte_budget, time_budget_ms)

The built-in test keys (row_count, freshness, null_count, etc.) get
their SQL generated by this module, not by the caller.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Optional

BUILTIN_TEST_KEYS = (
    "row_count",
    "freshness",
    "null_count",
    "null_fraction",
    "unique",
    "accepted_values",
    "regex",
    "min_max",
    "schema_column_presence",
    "custom_sql",
    "table_comparison",
)

FORBIDDEN_TOKENS = (
    "INSERT",
    "UPDATE",
    "DELETE",
    "DROP",
    "TRUNCATE",
    "CREATE",
    "MERGE",
    "CALL",
    "GRANT",
    "REVOKE",
    "ALTER",
    "OPTIMIZE",
    "VACUUM",
    "REFRESH",
    "COMMENT ON",
    "USE CATALOG",
    "USE SCHEMA",
)

# Max values we'll ever allow a caller to request. Individual plans may
# set smaller budgets.
MAX_ROW_BUDGET = 100_000
MAX_BYTE_BUDGET = 64 * 1024 * 1024  # 64 MiB
MAX_TIME_BUDGET_MS = 60_000  # 1 minute


@dataclass(frozen=True)
class CustomSqlValidation:
    ok: bool
    reason: str = ""
    normalized: str = ""


def _strip_comments(sql: str) -> str:
    # Remove /* ... */ block comments and -- line comments. Cheap enough
    # for pre-execution validation.
    block = re.sub(r"/\*.*?\*/", " ", sql, flags=re.S)
    line = re.sub(r"--[^\n]*", " ", block)
    return line


def validate_custom_sql(
    sql: str,
    *,
    target_entity_fqn: str,
    allowed_comparisons: Iterable[str] = (),
) -> CustomSqlValidation:
    if not sql or not sql.strip():
        return CustomSqlValidation(ok=False, reason="Custom SQL is empty.")
    cleaned = _strip_comments(sql).strip()
    # No trailing semicolons (reject chained statements).
    statements = [part for part in cleaned.split(";") if part.strip()]
    if len(statements) != 1:
        return CustomSqlValidation(
            ok=False,
            reason="Custom SQL must be a single statement (no ';' chaining).",
        )
    statement = statements[0].strip()
    upper = statement.upper()
    # SELECT-only.
    if not upper.startswith("SELECT") and not upper.startswith("WITH"):
        return CustomSqlValidation(
            ok=False,
            reason="Custom SQL must start with SELECT or WITH.",
        )
    for token in FORBIDDEN_TOKENS:
        pattern = r"\b" + re.escape(token) + r"\b"
        if re.search(pattern, upper):
            return CustomSqlValidation(
                ok=False,
                reason=f"Custom SQL may not contain {token}.",
            )
    # Must reference the target entity FQN (case-insensitive). We accept
    # either the fully-qualified form, the last two segments (schema.table),
    # or any allowed comparison entity.
    lowered = statement.lower()
    candidates = [target_entity_fqn.lower(), *[c.lower() for c in allowed_comparisons]]
    # allow schema.table if fqn has 3 segments
    if target_entity_fqn.count(".") >= 2:
        candidates.append(".".join(target_entity_fqn.split(".")[-2:]).lower())
    if not any(candidate in lowered for candidate in candidates if candidate):
        return CustomSqlValidation(
            ok=False,
            reason=(
                "Custom SQL must reference the target entity "
                f"({target_entity_fqn}) or an approved comparison entity."
            ),
        )
    return CustomSqlValidation(ok=True, normalized=statement)


@dataclass(frozen=True)
class BudgetCheck:
    ok: bool
    reason: str = ""
    row_budget: int = 0
    byte_budget: int = 0
    time_budget_ms: int = 0


def check_budgets(
    *,
    row_budget: Optional[int],
    byte_budget: Optional[int],
    time_budget_ms: Optional[int],
) -> BudgetCheck:
    row = int(row_budget or 0)
    byte = int(byte_budget or 0)
    ms = int(time_budget_ms or 0)
    if row < 0 or byte < 0 or ms < 0:
        return BudgetCheck(ok=False, reason="Budgets must be non-negative.")
    if row > MAX_ROW_BUDGET:
        return BudgetCheck(
            ok=False, reason=f"row_budget exceeds global cap ({MAX_ROW_BUDGET})."
        )
    if byte > MAX_BYTE_BUDGET:
        return BudgetCheck(
            ok=False, reason=f"byte_budget exceeds global cap ({MAX_BYTE_BUDGET})."
        )
    if ms > MAX_TIME_BUDGET_MS:
        return BudgetCheck(
            ok=False, reason=f"time_budget_ms exceeds global cap ({MAX_TIME_BUDGET_MS})."
        )
    return BudgetCheck(
        ok=True,
        row_budget=min(row or MAX_ROW_BUDGET, MAX_ROW_BUDGET),
        byte_budget=min(byte or MAX_BYTE_BUDGET, MAX_BYTE_BUDGET),
        time_budget_ms=min(ms or MAX_TIME_BUDGET_MS, MAX_TIME_BUDGET_MS),
    )


def summarize_run_results(
    results: List[Dict[str, Any]],
) -> Dict[str, int]:
    """Return counts per outcome for a quality_runs.summary_json value."""
    buckets = {"passed": 0, "failed": 0, "errored": 0, "skipped": 0}
    for record in results:
        outcome = str(record.get("outcome") or "").strip().lower()
        if outcome in buckets:
            buckets[outcome] += 1
    return buckets
