(function (global) {
  const asset = (fqn, data) => ({ fqn, ...data });

  const ASSETS = [
    asset("prod.silver.ap_self_assessed_tax_dist_history", {
      name: "ap_self_assessed_tax_dist_history",
      catalog: "prod",
      schema: "silver",
      objectType: "Streaming Table",
      description:
        "Latest-state history table for AP_SELF_ASSESSED_TAX_DIST_ALL, retained from sourced history to support downstream reconciliation and auditability.",
      coverageScore: 41,
      rows: "62,548",
      format: "delta",
      size: "8.2 MB",
      files: "4",
      domain: "Finance",
      tier: "Tier 1",
      certification: "Certified",
      sensitivity: "Confidential",
      criticality: "Business Critical",
      openRequests: 0,
      owners: [
        { name: "Maya Patel", title: "Technical Owner" },
        { name: "Darren Cole", title: "Data Steward" },
      ],
      tags: ["streaming", "audit", "fscm"],
      relatedAssets: ["prod.silver.ap_self_assessed_tax_dist", "dev.gold.z_gl_glsd_report_v"],
      preview: [
        { period: "2026-03-19", total_rows: "62,548", late_rows: "12", source: "SFTP" },
        { period: "2026-03-18", total_rows: "62,401", late_rows: "15", source: "SFTP" },
        { period: "2026-03-17", total_rows: "62,119", late_rows: "9", source: "SFTP" },
      ],
      columns: [
        { name: "invoice_distribution_id", type: "string", description: "Primary business key." },
        { name: "self_assessed_tax_amount", type: "decimal(18,2)", description: "Tax amount captured from source." },
        { name: "source_system", type: "string", description: "Originating upstream system." },
        { name: "ingest_ts", type: "timestamp", description: "Batch ingest timestamp." },
      ],
    }),
    asset("prod.silver.ap_self_assessed_tax_dist", {
      name: "ap_self_assessed_tax_dist",
      catalog: "prod",
      schema: "silver",
      objectType: "Streaming Table",
      description:
        "Raw append-only ingestion of AP_SELF_ASSESSED_TAX_DIST_ALL from SFTP CSV exports. All columns are strings.",
      coverageScore: 35,
      rows: "125,069",
      format: "delta",
      size: "6.7 MB",
      files: "2",
      domain: "Finance",
      tier: "Tier 1",
      certification: "Certified",
      sensitivity: "Confidential",
      criticality: "Business Critical",
      openRequests: 0,
      owners: [],
      tags: ["streaming", "oracle_fscm", "bronze"],
      relatedAssets: ["prod.silver.ap_self_assessed_tax_dist_history", "dev.gold.z_gl_glsd_report_v"],
      preview: [
        { invoice_distribution_id: "INV-90422", amount: "144.12", currency: "USD", source: "SFTP" },
        { invoice_distribution_id: "INV-90423", amount: "219.48", currency: "USD", source: "SFTP" },
        { invoice_distribution_id: "INV-90424", amount: "99.50", currency: "USD", source: "SFTP" },
      ],
      columns: [
        { name: "invoice_distribution_id", type: "string", description: "Primary business key." },
        { name: "amount", type: "string", description: "Raw string ingest from source CSV." },
        { name: "currency", type: "string", description: "ISO currency code." },
        { name: "source_system", type: "string", description: "Originating upstream system." },
      ],
    }),
    asset("dev.gold.z_gl_glsd_report_v", {
      name: "z_gl_glsd_report_v",
      catalog: "dev",
      schema: "gold",
      objectType: "View",
      description:
        "Curated report view used by finance and operations for tax distribution analysis.",
      coverageScore: 68,
      rows: "24,110",
      format: "view",
      size: "—",
      files: "—",
      domain: "Reporting",
      tier: "Tier 2",
      certification: "Needs Review",
      sensitivity: "Internal",
      criticality: "Standard",
      openRequests: 1,
      owners: [{ name: "Sofia Reyes", title: "Analytics Owner" }],
      tags: ["reporting", "curated"],
      relatedAssets: ["prod.silver.ap_self_assessed_tax_dist"],
      preview: [
        { report_date: "2026-03-19", amount: "4,884,502.81", status: "Final" },
        { report_date: "2026-03-18", amount: "4,753,120.33", status: "Final" },
        { report_date: "2026-03-17", amount: "4,671,900.55", status: "Final" },
      ],
      columns: [
        { name: "report_date", type: "date", description: "Report slice date." },
        { name: "amount", type: "decimal(18,2)", description: "Aggregated amount." },
        { name: "status", type: "string", description: "Publish status." },
      ],
    }),
    asset("dev.gold.z_gl_glsd_report", {
      name: "z_gl_glsd_report",
      catalog: "dev",
      schema: "gold",
      objectType: "Streaming Table",
      description: "Primary gold-layer report table powering downstream dashboards and extracts.",
      coverageScore: 61,
      rows: "19,808",
      format: "delta",
      size: "4.1 MB",
      files: "3",
      domain: "Reporting",
      tier: "Tier 2",
      certification: "Needs Review",
      sensitivity: "Internal",
      criticality: "Standard",
      openRequests: 0,
      owners: [{ name: "Sofia Reyes", title: "Analytics Owner" }],
      tags: ["reporting", "gold"],
      relatedAssets: ["dev.gold.z_gl_glsd_report_v"],
      preview: [
        { report_date: "2026-03-19", summary: "Ready for publish", status: "Green" },
        { report_date: "2026-03-18", summary: "Awaiting steward review", status: "Amber" },
        { report_date: "2026-03-17", summary: "Ready for publish", status: "Green" },
      ],
      columns: [
        { name: "report_date", type: "date", description: "Report slice date." },
        { name: "summary", type: "string", description: "Brief status summary." },
        { name: "status", type: "string", description: "Publish status." },
      ],
    }),
    asset("prod.gold.customer_gold_360", {
      name: "customer_gold_360",
      catalog: "prod",
      schema: "gold",
      objectType: "Table",
      description:
        "Unified customer profile table with harmonized identifiers, segment rollups, and engagement metrics.",
      coverageScore: 78,
      rows: "1,148,022",
      format: "delta",
      size: "32.8 MB",
      files: "12",
      domain: "Customer",
      tier: "Tier 1",
      certification: "Certified",
      sensitivity: "Restricted",
      criticality: "Mission Critical",
      openRequests: 0,
      owners: [
        { name: "Avery Shah", title: "Business Owner" },
        { name: "Maya Patel", title: "Technical Owner" },
      ],
      tags: ["customer", "gold", "pii"],
      relatedAssets: ["prod.gold.customer_lifetime_value"],
      preview: [
        { customer_id: "C-1008", segment: "Enterprise", health_score: "91", region: "NA" },
        { customer_id: "C-1114", segment: "Mid-Market", health_score: "84", region: "EMEA" },
        { customer_id: "C-1235", segment: "SMB", health_score: "72", region: "APAC" },
      ],
      columns: [
        { name: "customer_id", type: "string", description: "Canonical customer key." },
        { name: "segment", type: "string", description: "Commercial segment." },
        { name: "health_score", type: "int", description: "Composite customer health score." },
        { name: "region", type: "string", description: "Operating region." },
      ],
    }),
    asset("prod.gold.customer_lifetime_value", {
      name: "customer_lifetime_value",
      catalog: "prod",
      schema: "gold",
      objectType: "View",
      description:
        "Customer value model used by sales and finance for forecasting and priority account planning.",
      coverageScore: 71,
      rows: "98,420",
      format: "view",
      size: "—",
      files: "—",
      domain: "Customer",
      tier: "Tier 1",
      certification: "Certified",
      sensitivity: "Restricted",
      criticality: "Business Critical",
      openRequests: 1,
      owners: [{ name: "Avery Shah", title: "Business Owner" }],
      tags: ["forecasting", "customer", "value"],
      relatedAssets: ["prod.gold.customer_gold_360"],
      preview: [
        { customer_id: "C-1008", clv: "$91,200", status: "Healthy" },
        { customer_id: "C-1114", clv: "$73,800", status: "Watch" },
        { customer_id: "C-1235", clv: "$48,200", status: "Healthy" },
      ],
      columns: [
        { name: "customer_id", type: "string", description: "Canonical customer key." },
        { name: "clv", type: "decimal(18,2)", description: "Predicted lifetime value." },
        { name: "status", type: "string", description: "Forecast state." },
      ],
    }),
    asset("bronze.oracle_fscm.ap_invoice_batches", {
      name: "ap_invoice_batches",
      catalog: "bronze",
      schema: "oracle_fscm",
      objectType: "Table",
      description:
        "Landing table for batch invoice headers and source keys prior to standardization.",
      coverageScore: 33,
      rows: "482,204",
      format: "delta",
      size: "14.9 MB",
      files: "7",
      domain: "Finance",
      tier: "Tier 3",
      certification: "Needs Review",
      sensitivity: "Confidential",
      criticality: "Standard",
      openRequests: 2,
      owners: [],
      tags: ["oracle", "ingest", "finance"],
      relatedAssets: ["prod.silver.ap_self_assessed_tax_dist"],
      preview: [
        { batch_id: "B-9102", source: "Oracle ERP", invoice_count: "419", status: "Loaded" },
        { batch_id: "B-9103", source: "Oracle ERP", invoice_count: "381", status: "Loaded" },
        { batch_id: "B-9104", source: "Oracle ERP", invoice_count: "408", status: "Loaded" },
      ],
      columns: [
        { name: "batch_id", type: "string", description: "Batch identifier." },
        { name: "invoice_count", type: "int", description: "Invoices in the batch." },
        { name: "status", type: "string", description: "Load state." },
      ],
    }),
    asset("bronze.oracle_fscm.payment_ledger", {
      name: "payment_ledger",
      catalog: "bronze",
      schema: "oracle_fscm",
      objectType: "Table",
      description: "Ledger of payment events used to reconcile invoices and vendor remittances.",
      coverageScore: 29,
      rows: "1,920,331",
      format: "delta",
      size: "38.4 MB",
      files: "14",
      domain: "Finance",
      tier: "Tier 3",
      certification: "Needs Review",
      sensitivity: "Confidential",
      criticality: "Standard",
      openRequests: 4,
      owners: [{ name: "Jordan Lee", title: "Operations Owner" }],
      tags: ["ledger", "payments"],
      relatedAssets: ["prod.silver.ap_self_assessed_tax_dist"],
      preview: [
        { payment_id: "P-50011", amount: "108.22", currency: "USD", status: "Cleared" },
        { payment_id: "P-50012", amount: "220.99", currency: "USD", status: "Cleared" },
        { payment_id: "P-50013", amount: "40.83", currency: "USD", status: "Pending" },
      ],
      columns: [
        { name: "payment_id", type: "string", description: "Payment identifier." },
        { name: "amount", type: "decimal(18,2)", description: "Payment amount." },
        { name: "status", type: "string", description: "Payment state." },
      ],
    }),
  ];

  const GRAPH_PRESETS = {
    "prod.silver.ap_self_assessed_tax_dist_history": {
      data: {
        nodes: [
          {
            id: "focus",
            assetFqn: "prod.silver.ap_self_assessed_tax_dist_history",
            label: "ap_self_assessed_tax_dist_history",
            subtitle: "prod / silver",
            kicker: "Focus",
            kind: "Streaming Table",
            role: "focus",
            depth: 0,
            x: 50,
            y: 50,
            foot: ["Certified", "Business Critical"],
          },
          {
            id: "up-1",
            label: "Pipeline producing ap_self_assessed_tax_dist_history",
            subtitle: "ID 86fbd398...6de3 · 4 runs",
            kicker: "Pipeline",
            kind: "Pipeline",
            role: "source",
            depth: 1,
            x: 20,
            y: 28,
            foot: ["2 upstream assets"],
          },
          {
            id: "up-2",
            assetFqn: "prod.silver.ap_self_assessed_tax_dist",
            label: "ap_self_assessed_tax_dist",
            subtitle: "prod / silver",
            kicker: "Source",
            kind: "Streaming Table",
            role: "source",
            depth: 1,
            x: 20,
            y: 68,
            foot: ["Owner gap"],
          },
          {
            id: "up-3",
            label: "Notebook 1313903910442322",
            subtitle: "Run a82e7f85...9456",
            kicker: "Notebook",
            kind: "Notebook",
            role: "source",
            depth: 2,
            x: 16,
            y: 46,
            foot: ["3 runs"],
          },
          {
            id: "down-1",
            assetFqn: "dev.gold.z_gl_glsd_report_v",
            label: "z_gl_glsd_report_v",
            subtitle: "dev / gold",
            kicker: "Target",
            kind: "View",
            role: "target",
            depth: 1,
            x: 80,
            y: 25,
            foot: ["Certified consumer"],
          },
          {
            id: "down-2",
            label: "DBSQL Query consuming ap_self_assessed_tax_dist_history",
            subtitle: "ID f9485703...e0a3 · 3 runs",
            kicker: "DBSQL Query",
            kind: "DBSQL Query",
            role: "target",
            depth: 1,
            x: 80,
            y: 55,
            foot: ["4 statements"],
          },
          {
            id: "down-3",
            label: "Pipeline consuming ap_self_assessed_tax_dist_history",
            subtitle: "ID b3de3b8e...306f · Run 606d4966...8317",
            kicker: "Pipeline",
            kind: "Pipeline",
            role: "target",
            depth: 1,
            x: 80,
            y: 82,
            foot: ["Orchestrated"],
          },
          {
            id: "down-4",
            label: "Notebook consuming ap_self_assessed_tax_dist_history",
            subtitle: "ID 1313903910442322 · Run a82e7f85...9456",
            kicker: "Notebook",
            kind: "Notebook",
            role: "target",
            depth: 2,
            x: 84,
            y: 38,
            foot: ["Interactive"],
          },
        ],
        edges: [
          { source: "up-1", target: "focus", depth: 1 },
          { source: "up-2", target: "focus", depth: 1 },
          { source: "up-3", target: "focus", depth: 2 },
          { source: "focus", target: "down-1", depth: 1 },
          { source: "focus", target: "down-2", depth: 1 },
          { source: "focus", target: "down-3", depth: 1 },
          { source: "focus", target: "down-4", depth: 2 },
        ],
      },
      operational: {
        nodes: [
          {
            id: "focus",
            assetFqn: "prod.silver.ap_self_assessed_tax_dist_history",
            label: "ap_self_assessed_tax_dist_history",
            subtitle: "Focus asset",
            kicker: "Focus",
            kind: "Streaming Table",
            role: "focus",
            depth: 0,
            x: 50,
            y: 48,
            foot: ["Operational center"],
          },
          {
            id: "up-1",
            label: "Pipeline producing ap_self_assessed_tax_dist_history",
            subtitle: "4 runs · 2 upstream assets",
            kicker: "Pipeline",
            kind: "Pipeline",
            role: "source",
            depth: 1,
            x: 21,
            y: 28,
            foot: ["Recent run 8m ago"],
          },
          {
            id: "up-2",
            label: "Notebook 1313903910442322",
            subtitle: "ID 1313903910442322",
            kicker: "Notebook",
            kind: "Notebook",
            role: "source",
            depth: 1,
            x: 21,
            y: 68,
            foot: ["Authoring"],
          },
          {
            id: "down-1",
            label: "DBSQL Query consuming ap_self_assessed_tax_dist_history",
            subtitle: "3 runs · 1 downstream asset",
            kicker: "DBSQL Query",
            kind: "DBSQL Query",
            role: "target",
            depth: 1,
            x: 79,
            y: 28,
            foot: ["Analyst entry point"],
          },
          {
            id: "down-2",
            label: "Notebook consuming ap_self_assessed_tax_dist_history",
            subtitle: "Run a82e7f85...9456",
            kicker: "Notebook",
            kind: "Notebook",
            role: "target",
            depth: 1,
            x: 79,
            y: 68,
            foot: ["Exploration"],
          },
          {
            id: "down-3",
            label: "Pipeline consuming ap_self_assessed_tax_dist_history",
            subtitle: "Run 606d4966...8317",
            kicker: "Pipeline",
            kind: "Pipeline",
            role: "target",
            depth: 2,
            x: 84,
            y: 52,
            foot: ["Batch output"],
          },
        ],
        edges: [
          { source: "up-1", target: "focus", depth: 1 },
          { source: "up-2", target: "focus", depth: 1 },
          { source: "focus", target: "down-1", depth: 1 },
          { source: "focus", target: "down-2", depth: 1 },
          { source: "focus", target: "down-3", depth: 2 },
        ],
      },
    },
    "prod.silver.ap_self_assessed_tax_dist": {
      data: {
        nodes: [
          {
            id: "focus",
            assetFqn: "prod.silver.ap_self_assessed_tax_dist",
            label: "ap_self_assessed_tax_dist",
            subtitle: "prod / silver",
            kicker: "Focus",
            kind: "Streaming Table",
            role: "focus",
            depth: 0,
            x: 50,
            y: 50,
            foot: ["Certified", "High trust"],
          },
          {
            id: "up-1",
            label: "Pipeline producing ap_self_assessed_tax_dist",
            subtitle: "ID 86fbd398...6de3 · 4 runs",
            kicker: "Pipeline",
            kind: "Pipeline",
            role: "source",
            depth: 1,
            x: 20,
            y: 30,
            foot: ["Source of truth"],
          },
          {
            id: "up-2",
            assetFqn: "bronze.oracle_fscm.ap_invoice_batches",
            label: "ap_invoice_batches",
            subtitle: "bronze / oracle_fscm",
            kicker: "Source",
            kind: "Table",
            role: "source",
            depth: 1,
            x: 18,
            y: 68,
            foot: ["Landing table"],
          },
          {
            id: "down-1",
            assetFqn: "prod.silver.ap_self_assessed_tax_dist_history",
            label: "ap_self_assessed_tax_dist_history",
            subtitle: "prod / silver",
            kicker: "Target",
            kind: "Streaming Table",
            role: "target",
            depth: 1,
            x: 80,
            y: 28,
            foot: ["History tracking"],
          },
          {
            id: "down-2",
            assetFqn: "dev.gold.z_gl_glsd_report_v",
            label: "z_gl_glsd_report_v",
            subtitle: "dev / gold",
            kicker: "Target",
            kind: "View",
            role: "target",
            depth: 1,
            x: 81,
            y: 56,
            foot: ["Report consumer"],
          },
          {
            id: "down-3",
            label: "DBSQL Query consuming ap_self_assessed_tax_dist",
            subtitle: "ID f9485703...e0a3 · 3 runs",
            kicker: "DBSQL Query",
            kind: "DBSQL Query",
            role: "target",
            depth: 2,
            x: 79,
            y: 82,
            foot: ["Analyst query"],
          },
        ],
        edges: [
          { source: "up-1", target: "focus", depth: 1 },
          { source: "up-2", target: "focus", depth: 1 },
          { source: "focus", target: "down-1", depth: 1 },
          { source: "focus", target: "down-2", depth: 1 },
          { source: "focus", target: "down-3", depth: 2 },
        ],
      },
      operational: {
        nodes: [
          {
            id: "focus",
            assetFqn: "prod.silver.ap_self_assessed_tax_dist",
            label: "ap_self_assessed_tax_dist",
            subtitle: "Focus asset",
            kicker: "Focus",
            kind: "Streaming Table",
            role: "focus",
            depth: 0,
            x: 50,
            y: 48,
            foot: ["Operational center"],
          },
          {
            id: "up-1",
            label: "Pipeline producing ap_self_assessed_tax_dist",
            subtitle: "4 runs",
            kicker: "Pipeline",
            kind: "Pipeline",
            role: "source",
            depth: 1,
            x: 20,
            y: 30,
            foot: ["Producer workload"],
          },
          {
            id: "down-1",
            label: "DBSQL Query consuming ap_self_assessed_tax_dist",
            subtitle: "3 runs",
            kicker: "DBSQL Query",
            kind: "DBSQL Query",
            role: "target",
            depth: 1,
            x: 80,
            y: 28,
            foot: ["Consumer workload"],
          },
          {
            id: "down-2",
            label: "Notebook consuming ap_self_assessed_tax_dist",
            subtitle: "Authoring surface",
            kicker: "Notebook",
            kind: "Notebook",
            role: "target",
            depth: 1,
            x: 80,
            y: 68,
            foot: ["Review and exploration"],
          },
        ],
        edges: [
          { source: "up-1", target: "focus", depth: 1 },
          { source: "focus", target: "down-1", depth: 1 },
          { source: "focus", target: "down-2", depth: 1 },
        ],
      },
    },
  };

  const GOVERNANCE = {
    metrics: [
      { label: "Assets", value: 672 },
      { label: "Needs attention", value: 91 },
      { label: "Certified", value: 218 },
      { label: "With stewards", value: 197 },
      { label: "Sensitive assets", value: 86 },
      { label: "Open requests", value: 11 },
    ],
    backlog: [
      {
        title: "Assign owner to ap_self_assessed_tax_dist",
        asset: "prod.silver.ap_self_assessed_tax_dist",
        status: "Needs Owner",
        note: "High-usage finance feed with no active business owner.",
      },
      {
        title: "Review certification on z_gl_glsd_report_v",
        asset: "dev.gold.z_gl_glsd_report_v",
        status: "Needs Review",
        note: "Report is widely consumed but still needs steward signoff.",
      },
      {
        title: "Validate sensitivity on customer_gold_360",
        asset: "prod.gold.customer_gold_360",
        status: "Restricted",
        note: "PII-heavy customer table should stay tightly controlled.",
      },
    ],
    glossary: [
      { term: "Customer", definition: "A person or organization receiving goods or services." },
      { term: "Certified", definition: "Approved for general business use." },
      { term: "Sensitive", definition: "Contains regulated or protected data." },
      { term: "Domain", definition: "Business area that owns and curates an asset family." },
    ],
  };

  const SHELL = {
    metrics: [
      { label: "Assets", value: 672 },
      { label: "Needs attention", value: 91 },
      { label: "Certified", value: 218 },
      { label: "With stewards", value: 197 },
      { label: "Sensitive assets", value: 86 },
      { label: "Open requests", value: 11 },
    ],
  };

  global.GOVHUB_DATA = {
    version: "modern-ui-static-1",
    apiBase: "/api",
    assets: ASSETS,
    assetIndex: Object.fromEntries(ASSETS.map((row) => [row.fqn, row])),
    discovery: {
      catalogs: ["All catalogs", "bronze", "dev", "prod"],
      domains: ["All domains", "Finance", "Customer", "Reporting"],
      tiers: ["All tiers", "Tier 1", "Tier 2", "Tier 3", "Tier 4"],
      certifications: ["All certifications", "Certified", "Needs Review", "Deprecated"],
      sensitivities: ["All sensitivities", "Public", "Internal", "Confidential", "Restricted"],
      views: ["All assets", "Needs owner", "Needs certification", "Certified", "High coverage"],
      sortOptions: ["Best match", "Coverage score", "Recently updated", "Open requests"],
      defaultQuery: "customer",
    },
    graphs: GRAPH_PRESETS,
    governance: GOVERNANCE,
    shell: SHELL,
    apiContract: {
      discoverySearch: "/api/discovery/search",
      assetDetail: "/api/assets/:fqn",
      lineage: "/api/lineage/:fqn",
      governanceSummary: "/api/governance/summary",
      glossary: "/api/governance/glossary",
    },
    help: [
      {
        title: "Discovery",
        body: "Search, filter, and open the most relevant asset directly from the result rail.",
      },
      {
        title: "Lineage",
        body: "Click any node to refocus the graph and see adjacent producers or consumers.",
      },
      {
        title: "Governance",
        body: "Review coverage, requests, glossary terms, and stewardship state in one place.",
      },
    ],
  };
})(window);
