#!/usr/bin/env python3
"""Assemble a clean Databricks bundle directory with built frontend assets."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from atlas.runtime_contract import required_frontend_bundle_paths, validate_frontend_bundle


# Required bundle artifacts include frontend/dist/index.html, frontend/dist/assets,
# and the frontend-generated build manifest. The filename remains a frontend
# compatibility artifact until the frontend build pipeline is renamed.
REQUIRED_FRONTEND_FILES = required_frontend_bundle_paths(ROOT)
BUNDLE_MARKER_PATH = ".atlas_bundle_manifest.json"
DATABRICKS_IGNORE_PATH = ".databricksignore"
DATABRICKS_IGNORE_CONTENT = """# Generated by scripts/prepare_bundle.py
.git/
.github/
.claude/
.codex/
.venv/
.vscode/
.idea/
.cursor/
.env
.env.*
__pycache__/
__MACOSX/
.pytest_cache/
.ruff_cache/
.mypy_cache/
.databricks/
.DS_Store
docs/branding/
docs/mockups/
docs/northstar_baseline_screenshots/
docs/screenshots/
frontend/node_modules/
*.png
*.jpg
*.jpeg
*.gif
*.webp
"""
PACKAGED_GITIGNORE_APPEND = """
# Generated by scripts/prepare_bundle.py
!frontend/dist/
!frontend/dist/**
!frontend/dist/atlas-build-manifest.json
"""


def _ignore(_directory: str, names: list[str]) -> set[str]:
    ignored = {
        ".git",
        ".github",
        ".claude",
        ".codex",
        ".venv",
        ".vscode",
        ".idea",
        ".cursor",
        "__pycache__",
        "__MACOSX",
        ".pytest_cache",
        ".ruff_cache",
        ".mypy_cache",
        ".databricks",
        ".DS_Store",
        "node_modules",
    }
    result: set[str] = set()
    for name in names:
        if name in ignored:
            result.add(name)
        elif name.startswith(".env"):
            result.add(name)
        else:
            directory = Path(_directory).resolve()
            # The packager writes its output directory under <ROOT>/build/.
            # Excluding the entire `build/` tree at the source root prevents
            # copytree from recursing into a destination that's actively
            # being written, which would otherwise spin into an unbounded
            # build/atlas-app/build/atlas-app/... loop.
            if directory == ROOT and name == "build":
                result.add(name)
                continue
            # Visual-QA captures sometimes leave behind a live Chrome user
            # data dir under docs/northstar_visual_qa/.../chrome-profile-*.
            # Those folders contain Unix sockets and lock files that
            # shutil.copytree cannot copy ("Operation not supported on
            # socket"), which fails the entire packaging step. Skip them
            # — the QA captures themselves (HTML, screenshots, metadata)
            # are intentionally bundled in docs/, but the live profile
            # state is not part of the deployable artifact.
            if name.startswith("chrome-profile"):
                result.add(name)
                continue
            if directory == ROOT and Path(name).suffix.lower() in {
                ".png",
                ".jpg",
                ".jpeg",
                ".gif",
                ".webp",
            }:
                result.add(name)
            elif directory == ROOT / "docs" and name in {
                "branding",
                "mockups",
                "northstar_baseline_screenshots",
                "screenshots",
            }:
                result.add(name)
    return result


def _validate_frontend_bundle() -> None:
    try:
        validate_frontend_bundle(ROOT)
    except RuntimeError as exc:
        raise SystemExit(str(exc)) from exc


def _looks_like_removed_legacy_shell(path: Path) -> bool:
    if not path.is_dir():
        return False
    if path.name.startswith(".") or path.name in {"frontend", "atlas", "tests", "scripts", "docs", "sql"}:
        return False
    return (path / "index.html").exists() and (
        (path / "assets").exists() or (path / "data.js").exists()
    )


def _prune_removed_legacy_shells(output_dir: Path) -> None:
    for child in output_dir.iterdir():
        if _looks_like_removed_legacy_shell(child):
            shutil.rmtree(child)


def _write_bundle_manifest(output_dir: Path) -> None:
    build_manifest_path = output_dir / "frontend" / "dist" / "atlas-build-manifest.json"
    build_manifest = json.loads(build_manifest_path.read_text(encoding="utf-8"))
    (output_dir / BUNDLE_MARKER_PATH).write_text(
        json.dumps(
            {
                "preparedAt": datetime.now(timezone.utc).isoformat(),
                "preparedFrom": str(ROOT),
                "buildId": build_manifest.get("buildId") or "",
                "sourceHash": build_manifest.get("sourceHash") or "",
                "frontendBuildManifest": "frontend/dist/atlas-build-manifest.json",
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )


def _write_databricksignore(output_dir: Path) -> None:
    (output_dir / DATABRICKS_IGNORE_PATH).write_text(
        DATABRICKS_IGNORE_CONTENT,
        encoding="utf-8",
    )


def _rewrite_packaged_gitignore(output_dir: Path) -> None:
    gitignore_path = output_dir / ".gitignore"
    if not gitignore_path.exists():
        return
    content = gitignore_path.read_text(encoding="utf-8")
    if "!frontend/dist/**" in content:
        return
    normalized = content.rstrip("\n")
    gitignore_path.write_text(
        f"{normalized}{PACKAGED_GITIGNORE_APPEND}",
        encoding="utf-8",
    )


APP_YAML_PATH = "app.yaml"
APP_YAML_HEADER = (
    "# Databricks App configuration — single source of truth.\n"
    "# Docs: https://docs.databricks.com/en/dev-tools/databricks-apps/app-config.html\n"
    "#\n"
    "# This file is REGENERATED by scripts/prepare_bundle.py when --target is\n"
    "# supplied. The Databricks Apps platform reads env vars only from app.yaml\n"
    "# in the deployed source code; the databricks_app Terraform resource has no\n"
    "# config/env attribute, so values defined in databricks.yml under\n"
    "# resources.apps.atlas.config.env never reach the running app via\n"
    "# `databricks bundle deploy` alone. The packaging step resolves per-target\n"
    "# variables via `databricks bundle validate -o json -t <target>` and bakes\n"
    "# the result here, so per-target env values are honored at runtime while\n"
    "# the in-repo app.yaml stays portable.\n"
)


def _resolve_target_app_config(
    target: str,
    profile: str | None,
    extra_vars: Iterable[str] = (),
) -> dict[str, Any]:
    """Return the bundle-validated `resources.apps.atlas` config for `target`.

    Runs `databricks bundle validate -o json -t <target>` against the source
    repository, which fully resolves variables, defaults, and per-target
    overrides defined in databricks.yml.
    """
    cmd = ["databricks", "bundle", "validate", "-o", "json", "-t", target]
    if profile:
        cmd.extend(["--profile", profile])
    for var_assignment in extra_vars:
        cmd.append(f"--var={var_assignment}")
    try:
        result = subprocess.run(
            cmd,
            cwd=str(ROOT),
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError as exc:
        raise SystemExit(
            "`databricks` CLI not found on PATH. Install the Databricks CLI before "
            "running prepare_bundle.py with --target."
        ) from exc
    except subprocess.CalledProcessError as exc:
        stderr = exc.stderr.strip() if exc.stderr else ""
        raise SystemExit(
            f"`databricks bundle validate -t {target}` failed with exit "
            f"code {exc.returncode}.\n{stderr}"
        ) from exc

    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise SystemExit(
            "Could not parse JSON from `databricks bundle validate -o json`."
        ) from exc

    apps = (payload.get("resources") or {}).get("apps") or {}
    if "atlas" not in apps:
        raise SystemExit(
            f"Bundle target '{target}' did not produce a resources.apps.atlas "
            "definition. Confirm the target name and that databricks.yml defines "
            "the atlas app."
        )
    return (apps["atlas"].get("config") or {})


def _yaml_quote(value: str) -> str:
    """Quote a YAML scalar safely. Preserves an empty string as ``\"\"``."""
    if value is None:
        return '""'
    text = str(value)
    # Escape backslashes and double quotes for double-quoted YAML scalars.
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _render_app_yaml(config: dict[str, Any], target: str) -> str:
    command = config.get("command") or []
    env_entries = config.get("env") or []

    lines: list[str] = []
    lines.append(APP_YAML_HEADER)
    lines.append(f"# Generated for bundle target: {target}\n")
    lines.append("\n")

    lines.append("command:\n")
    if command:
        for token in command:
            lines.append(f"  - {_yaml_quote(token)}\n")
    else:
        # Fallback to the canonical launcher if the bundle target omits command.
        lines.append('  - "python"\n')
        lines.append('  - "run_app.py"\n')
    lines.append("\n")

    lines.append("env:\n")
    if not env_entries:
        lines.append("  []\n")
    for entry in env_entries:
        name = entry.get("name")
        if not name:
            continue
        lines.append(f"  - name: {name}\n")
        if "value_from" in entry and entry["value_from"] is not None:
            lines.append(f"    valueFrom: {_yaml_quote(entry['value_from'])}\n")
        elif "valueFrom" in entry and entry["valueFrom"] is not None:
            lines.append(f"    valueFrom: {_yaml_quote(entry['valueFrom'])}\n")
        else:
            value = entry.get("value", "")
            lines.append(f"    value: {_yaml_quote(value)}\n")

    return "".join(lines)


def _write_target_app_yaml(
    output_dir: Path,
    target: str,
    profile: str | None,
    extra_vars: Iterable[str] = (),
) -> None:
    config = _resolve_target_app_config(target, profile, extra_vars)
    rendered = _render_app_yaml(config, target)
    (output_dir / APP_YAML_PATH).write_text(rendered, encoding="utf-8")


def build_bundle(
    output_dir: Path,
    target: str | None = None,
    profile: str | None = None,
    extra_vars: Iterable[str] = (),
) -> None:
    _validate_frontend_bundle()
    if output_dir.exists():
        shutil.rmtree(output_dir)
    shutil.copytree(ROOT, output_dir, ignore=_ignore)
    _prune_removed_legacy_shells(output_dir)
    _write_databricksignore(output_dir)
    _rewrite_packaged_gitignore(output_dir)
    _write_bundle_manifest(output_dir)
    if target:
        _write_target_app_yaml(output_dir, target, profile, extra_vars)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, help="Output directory for the packaged bundle.")
    parser.add_argument(
        "--target",
        default=None,
        help=(
            "Bundle target to bake into the packaged app.yaml (e.g. dev, prod). "
            "When supplied, runs `databricks bundle validate -o json -t <target>` "
            "and overwrites <output>/app.yaml with the resolved env vars and "
            "command so per-target config is honored at runtime."
        ),
    )
    parser.add_argument(
        "--profile",
        default=None,
        help="Databricks CLI profile to use for `bundle validate`.",
    )
    parser.add_argument(
        "--var",
        action="append",
        default=[],
        help=(
            "Repeatable --var key=value passed through to `bundle validate` "
            "(e.g. --var=warehouse_id=...). Required when the target leaves "
            "warehouse_id unbound."
        ),
    )
    args = parser.parse_args()
    build_bundle(
        Path(args.output).resolve(),
        target=args.target,
        profile=args.profile,
        extra_vars=args.var,
    )


if __name__ == "__main__":
    main()
