#!/usr/bin/env python3
"""Assemble a clean Databricks bundle directory with built frontend assets."""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from atlas.runtime_contract import required_frontend_bundle_paths, validate_frontend_bundle


# Required bundle artifacts include frontend/dist/index.html, frontend/dist/assets,
# and the frontend-generated build manifest. The filename remains a frontend
# compatibility artifact until the frontend build pipeline is renamed.
REQUIRED_FRONTEND_FILES = required_frontend_bundle_paths(ROOT)
BUNDLE_MARKER_PATH = ".atlas_bundle_manifest.json"
DATABRICKS_IGNORE_PATH = ".databricksignore"
DATABRICKS_IGNORE_CONTENT = """# Generated by scripts/prepare_bundle.py
.git/
.github/
.claude/
.codex/
.venv/
.vscode/
.idea/
.cursor/
.env
.env.*
__pycache__/
__MACOSX/
.pytest_cache/
.ruff_cache/
.mypy_cache/
.databricks/
.DS_Store
docs/branding/
docs/mockups/
docs/northstar_baseline_screenshots/
docs/screenshots/
frontend/node_modules/
*.png
*.jpg
*.jpeg
*.gif
*.webp
"""
PACKAGED_GITIGNORE_APPEND = """
# Generated by scripts/prepare_bundle.py
!frontend/dist/
!frontend/dist/**
!frontend/dist/atlas-build-manifest.json
"""


def _ignore(_directory: str, names: list[str]) -> set[str]:
    ignored = {
        ".git",
        ".github",
        ".claude",
        ".codex",
        ".venv",
        ".vscode",
        ".idea",
        ".cursor",
        "__pycache__",
        "__MACOSX",
        ".pytest_cache",
        ".ruff_cache",
        ".mypy_cache",
        ".databricks",
        ".DS_Store",
        "node_modules",
    }
    result: set[str] = set()
    for name in names:
        if name in ignored:
            result.add(name)
        elif name.startswith(".env"):
            result.add(name)
        else:
            directory = Path(_directory).resolve()
            if directory == ROOT and Path(name).suffix.lower() in {
                ".png",
                ".jpg",
                ".jpeg",
                ".gif",
                ".webp",
            }:
                result.add(name)
            elif directory == ROOT / "docs" and name in {
                "branding",
                "mockups",
                "northstar_baseline_screenshots",
                "screenshots",
            }:
                result.add(name)
    return result


def _validate_frontend_bundle() -> None:
    try:
        validate_frontend_bundle(ROOT)
    except RuntimeError as exc:
        raise SystemExit(str(exc)) from exc


def _looks_like_removed_legacy_shell(path: Path) -> bool:
    if not path.is_dir():
        return False
    if path.name.startswith(".") or path.name in {"frontend", "atlas", "tests", "scripts", "docs", "sql"}:
        return False
    return (path / "index.html").exists() and (
        (path / "assets").exists() or (path / "data.js").exists()
    )


def _prune_removed_legacy_shells(output_dir: Path) -> None:
    for child in output_dir.iterdir():
        if _looks_like_removed_legacy_shell(child):
            shutil.rmtree(child)


def _write_bundle_manifest(output_dir: Path) -> None:
    build_manifest_path = output_dir / "frontend" / "dist" / "atlas-build-manifest.json"
    build_manifest = json.loads(build_manifest_path.read_text(encoding="utf-8"))
    (output_dir / BUNDLE_MARKER_PATH).write_text(
        json.dumps(
            {
                "preparedAt": datetime.now(timezone.utc).isoformat(),
                "preparedFrom": str(ROOT),
                "buildId": build_manifest.get("buildId") or "",
                "sourceHash": build_manifest.get("sourceHash") or "",
                "frontendBuildManifest": "frontend/dist/atlas-build-manifest.json",
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )


def _write_databricksignore(output_dir: Path) -> None:
    (output_dir / DATABRICKS_IGNORE_PATH).write_text(
        DATABRICKS_IGNORE_CONTENT,
        encoding="utf-8",
    )


def _rewrite_packaged_gitignore(output_dir: Path) -> None:
    gitignore_path = output_dir / ".gitignore"
    if not gitignore_path.exists():
        return
    content = gitignore_path.read_text(encoding="utf-8")
    if "!frontend/dist/**" in content:
        return
    normalized = content.rstrip("\n")
    gitignore_path.write_text(
        f"{normalized}{PACKAGED_GITIGNORE_APPEND}",
        encoding="utf-8",
    )


def build_bundle(output_dir: Path) -> None:
    _validate_frontend_bundle()
    if output_dir.exists():
        shutil.rmtree(output_dir)
    shutil.copytree(ROOT, output_dir, ignore=_ignore)
    _prune_removed_legacy_shells(output_dir)
    _write_databricksignore(output_dir)
    _rewrite_packaged_gitignore(output_dir)
    _write_bundle_manifest(output_dir)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, help="Output directory for the packaged bundle.")
    args = parser.parse_args()
    build_bundle(Path(args.output).resolve())


if __name__ == "__main__":
    main()
